import type { Product, Category, User, Order, Review } from "./types"

export const categories: Category[] = [
  { id: "1", name: "Cà phê", slug: "ca-phe", icon: "coffee", productCount: 15 },
  { id: "2", name: "Trà", slug: "tra", icon: "leaf", productCount: 12 },
  { id: "3", name: "Đá xay", slug: "da-xay", icon: "snowflake", productCount: 8 },
  { id: "4", name: "Nước ép & Sinh tố", slug: "nuoc-ep-sinh-to", icon: "citrus", productCount: 10 },
  { id: "5", name: "Bánh ngọt", slug: "banh-ngot", icon: "cake", productCount: 12 },
  { id: "6", name: "Snack & Đồ ăn nhẹ", slug: "snack-do-an-nhe", icon: "cookie", productCount: 8 },
  { id: "7", name: "Combo", slug: "combo", icon: "package", productCount: 6 },
  { id: "8", name: "Cà phê hạt", slug: "ca-phe-hat", icon: "bean", productCount: 10 },
]

export const products: Product[] = [
  // ============ CÀ PHÊ ============
  {
    id: "1",
    name: "Cà phê đen đá",
    slug: "ca-phe-den-da",
    description: "Cà phê đen truyền thống pha phin, đậm đà hương vị Việt Nam. Hạt cà phê Robusta được rang xay tươi mỗi ngày.",
    price: 25000,
    originalPrice: 30000,
    images: ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500"],
    category: categories[0],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L", "Đường": "Có thể điều chỉnh", "Đá": "Có thể điều chỉnh" },
    stock: 999,
    rating: 4.8,
    reviewCount: 156,
    isFeatured: true,
    discount: 17,
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Cà phê sữa đá",
    slug: "ca-phe-sua-da",
    description: "Cà phê sữa đá - thức uống quốc dân của người Việt. Sự kết hợp hoàn hảo giữa cà phê đậm đà và sữa đặc béo ngậy.",
    price: 29000,
    originalPrice: 35000,
    images: ["https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500"],
    category: categories[0],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L", "Đường": "Có thể điều chỉnh" },
    stock: 999,
    rating: 4.9,
    reviewCount: 234,
    isFeatured: true,
    discount: 17,
    createdAt: "2024-01-20",
  },
  {
    id: "3",
    name: "Bạc xỉu",
    slug: "bac-xiu",
    description: "Bạc xỉu - cà phê sữa phiên bản nhẹ nhàng hơn, nhiều sữa hơn, phù hợp cho những ai thích vị ngọt béo.",
    price: 32000,
    originalPrice: 38000,
    images: ["https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=500"],
    category: categories[0],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.7,
    reviewCount: 189,
    isFeatured: true,
    discount: 16,
    createdAt: "2024-03-10",
  },
  {
    id: "4",
    name: "Cappuccino",
    slug: "cappuccino",
    description: "Cappuccino chuẩn Ý với tỷ lệ hoàn hảo 1:1:1 giữa espresso, sữa nóng và bọt sữa mịn.",
    price: 45000,
    originalPrice: 52000,
    images: ["https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500"],
    category: categories[0],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.8,
    reviewCount: 145,
    isFeatured: true,
    discount: 13,
    createdAt: "2024-03-05",
  },
  {
    id: "5",
    name: "Caramel Macchiato",
    slug: "caramel-macchiato",
    description: "Caramel Macchiato với lớp sữa tươi mịn màng, espresso đậm đà và sốt caramel thơm ngọt.",
    price: 52000,
    originalPrice: 59000,
    images: ["https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=500"],
    category: categories[0],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.9,
    reviewCount: 198,
    isNew: true,
    isFeatured: true,
    discount: 12,
    createdAt: "2024-02-01",
  },

  // ============ TRÀ ============
  {
    id: "6",
    name: "Trà đào cam sả",
    slug: "tra-dao-cam-sa",
    description: "Trà đào cam sả thanh mát với đào ngâm thơm ngọt, cam tươi và sả thơm. Thức uống giải khát hoàn hảo.",
    price: 39000,
    originalPrice: 45000,
    images: ["https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=500"],
    category: categories[1],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.9,
    reviewCount: 267,
    isFeatured: true,
    discount: 13,
    createdAt: "2024-02-20",
  },
  {
    id: "7",
    name: "Trà vải",
    slug: "tra-vai",
    description: "Trà vải thơm ngọt với vải tươi ngâm, vị thanh mát dễ uống. Thức uống được yêu thích nhất mùa hè.",
    price: 39000,
    originalPrice: 45000,
    images: ["https://images.unsplash.com/photo-1558857563-b371033873b8?w=500"],
    category: categories[1],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.8,
    reviewCount: 189,
    isFeatured: true,
    discount: 13,
    createdAt: "2024-03-01",
  },
  {
    id: "8",
    name: "Trà matcha đá xay",
    slug: "tra-matcha-da-xay",
    description: "Trà matcha Nhật Bản xay đá mịn, vị trà xanh đậm đà, thơm ngon. Topping kem whip béo ngậy.",
    price: 49000,
    originalPrice: 55000,
    images: ["https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=500"],
    category: categories[1],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.9,
    reviewCount: 178,
    isNew: true,
    isFeatured: true,
    discount: 11,
    createdAt: "2024-02-15",
  },
  // ============ ĐÁ XAY ============
  {
    id: "9",
    name: "Chocolate đá xay",
    slug: "chocolate-da-xay",
    description: "Chocolate đá xay béo ngậy với bột cacao nguyên chất, sữa tươi và kem whip.",
    price: 49000,
    originalPrice: 55000,
    images: ["https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500"],
    category: categories[2],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.8,
    reviewCount: 167,
    isFeatured: true,
    discount: 11,
    createdAt: "2024-03-01",
  },
  {
    id: "10",
    name: "Cookies & Cream",
    slug: "cookies-cream",
    description: "Đá xay Cookies & Cream với bánh Oreo nghiền, kem vanilla và kem whip. Vị ngọt béo, giòn tan.",
    price: 52000,
    originalPrice: 59000,
    images: ["https://images.unsplash.com/photo-1577805947697-89e18249d767?w=500"],
    category: categories[2],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.9,
    reviewCount: 145,
    isNew: true,
    isFeatured: true,
    discount: 12,
    createdAt: "2024-02-10",
  },

  // ============ NƯỚC ÉP & SINH TỐ ============
  {
    id: "11",
    name: "Sinh tố bơ",
    slug: "sinh-to-bo",
    description: "Sinh tố bơ béo ngậy với bơ sáp chín, sữa đặc và đá xay. Thức uống bổ dưỡng, thơm ngon.",
    price: 45000,
    originalPrice: 52000,
    images: ["https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=500"],
    category: categories[3],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.9,
    reviewCount: 156,
    isFeatured: true,
    discount: 13,
    createdAt: "2024-01-25",
  },
  {
    id: "12",
    name: "Nước ép cam",
    slug: "nuoc-ep-cam",
    description: "Nước ép cam tươi 100% nguyên chất, không đường, giàu vitamin C. Tươi mát, bổ dưỡng.",
    price: 35000,
    originalPrice: 42000,
    images: ["https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500"],
    category: categories[3],
    brand: "NHH-Coffee",
    specs: { "Kích cỡ": "M/L" },
    stock: 999,
    rating: 4.7,
    reviewCount: 89,
    discount: 17,
    createdAt: "2024-02-01",
  },
  // ============ BÁNH NGỌT ============
  {
    id: "13",
    name: "Bánh tiramisu",
    slug: "banh-tiramisu",
    description: "Bánh tiramisu Ý chuẩn vị với lớp kem mascarpone mịn màng, bánh lady finger thấm cà phê espresso.",
    price: 55000,
    originalPrice: 65000,
    images: ["https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500"],
    category: categories[4],
    brand: "NHH-Coffee",
    specs: { "Khẩu phần": "1 miếng", "Bảo quản": "Ngăn mát tủ lạnh" },
    stock: 50,
    rating: 4.9,
    reviewCount: 189,
    isFeatured: true,
    discount: 15,
    createdAt: "2024-03-15",
  },
  {
    id: "14",
    name: "Croissant bơ",
    slug: "croissant-bo",
    description: "Croissant bơ Pháp với lớp vỏ giòn xốp, bên trong mềm mịn, thơm mùi bơ. Nướng tươi mỗi ngày.",
    price: 35000,
    originalPrice: 42000,
    images: ["https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500"],
    category: categories[4],
    brand: "NHH-Coffee",
    specs: { "Khẩu phần": "1 cái" },
    stock: 60,
    rating: 4.7,
    reviewCount: 167,
    discount: 17,
    createdAt: "2024-03-10",
  },
  // ============ COMBO ============
  {
    id: "15",
    name: "Combo sáng 1",
    slug: "combo-sang-1",
    description: "Combo sáng tiết kiệm: 1 Cà phê sữa đá + 1 Croissant bơ. Bữa sáng hoàn hảo để bắt đầu ngày mới.",
    price: 55000,
    originalPrice: 71000,
    images: ["https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500"],
    category: categories[6],
    brand: "NHH-Coffee",
    specs: { "Bao gồm": "Cà phê sữa đá + Croissant bơ" },
    stock: 999,
    rating: 4.8,
    reviewCount: 145,
    isFeatured: true,
    discount: 23,
    createdAt: "2024-02-01",
  },
  // ============ CÀ PHÊ HẠT ============
  {
    id: "16",
    name: "Cà phê hạt Arabica Đà Lạt",
    slug: "ca-phe-hat-arabica-da-lat",
    description: "Cà phê hạt Arabica Đà Lạt 100% nguyên chất. Hương thơm nhẹ nhàng, vị chua thanh đặc trưng.",
    price: 180000,
    originalPrice: 220000,
    images: ["https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500"],
    category: categories[7],
    brand: "NHH-Coffee",
    specs: { "Trọng lượng": "250g", "Xuất xứ": "Đà Lạt, Lâm Đồng", "Rang": "Medium Roast" },
    stock: 100,
    rating: 4.9,
    reviewCount: 89,
    isFeatured: true,
    discount: 18,
    createdAt: "2024-01-15",
  },
]


export const mockUser: User = {
  id: "1",
  email: "user@example.com",
  name: "Nguyễn Văn A",
  avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
  phone: "0901234567",
  address: "Hải Thịnh, Tỉnh Ninh Bình",
  createdAt: "2024-01-01",
}

export const mockOrders: Order[] = [
  {
    id: "ORD001",
    userId: "1",
    items: [
      { product: products[0], quantity: 2 },
      { product: products[12], quantity: 1 },
    ],
    total: 105000,
    status: "delivered",
    shippingAddress: "Hải Thịnh, Tỉnh Ninh Bình",
    paymentMethod: "COD",
    createdAt: "2024-03-01",
  },
  {
    id: "ORD002",
    userId: "1",
    items: [{ product: products[5], quantity: 2 }],
    total: 78000,
    status: "shipping",
    shippingAddress: "Hải Thịnh, Tỉnh Ninh Bình",
    paymentMethod: "Banking",
    createdAt: "2024-03-10",
  },
]

export const mockReviews: Review[] = [
  {
    id: "1",
    userId: "2",
    userName: "Trần Minh B",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    productId: "1",
    rating: 5,
    comment: "Cà phê rất ngon, đậm đà đúng vị. Sẽ quay lại ủng hộ!",
    createdAt: "2024-03-05",
  },
  {
    id: "2",
    userId: "3",
    userName: "Lê Thị C",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    productId: "1",
    rating: 4,
    comment: "Cà phê ngon, giao hàng nhanh. Rất hài lòng!",
    createdAt: "2024-03-08",
  },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
  }).format(price)
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.category.slug === categorySlug)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured)
}

export function getNewProducts(): Product[] {
  return products.filter((p) => p.isNew)
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowercaseQuery) ||
      p.brand.toLowerCase().includes(lowercaseQuery) ||
      p.description.toLowerCase().includes(lowercaseQuery),
  )
}
